version: '2'
services:
######################################
# SonarQube Container
######################################
  sonarqube:
    container_name: sonarqube
    network_mode: bridge
    image: petronetto/sonarqube-alpine
    ports:
      - 9000:9000
      - 9002:9002
    volumes:
      - ./samples:/data/samples
      - ./sonar-runner.properties:/opt/sonar-scanner-2.5.1/conf/sonar-runner.properties
      - ./sonar.properties:/opt/sonarqube/conf/sonar.properties
    links:
      - postgres
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres/sonar
######################################
# Postgres Container
######################################
  postgres:
    container_name: postgres
    network_mode: bridge
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar